services:
  app:
    build: .
    volumes:
      - ./public:/app/public
    environment:
      VIRTUAL_HOST: dl.localhost,dl.center
      LETSENCRYPT_EMAIL: letsencrypt@simkim.net
      LETSENCRYPT_HOST: dl.center
